server:
  port: 8080

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: backend

  profiles:
    active: dev

  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      properties:
        hibernate:
          enable_lazy_load_no_trans: true

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;

  data:
    rest:
      defaultMediaType: application/json
    web:
      pageable:
        default-page-size: 25

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
